Active storage
krossovok83/bookstore_per_step pull request #11
Opened 2022-02-22 20:45 UTC by krossovok83

• Images uploading/displaying for all imagable models and pages
• Storing of production images on S3
• Add buttons "View more" instead of pagination navbar
• Write tests

2022-02-23 20:46 UTC, papandreusa requested changes
1. check your PR:
many files that must be merged on previous steps are presented as new. 

2. You should store all your images on S3:

7 step
Images uploading/displaying for all imagable models and pages
Storing of production images on S3
Write tests (unit, feature) for your new code.

2022-02-23 20:46 UTC, papandreusa commented on Gemfile
>    gem "web-console"
indicate gem version, please

2022-02-23 20:46 UTC, papandreusa commented on config/initializers/active_admin.rb
> +# frozen_string_literal: true
this file must be already merged in master on previous steps

2022-02-23 20:46 UTC, papandreusa commented on spec/rails_helper.rb
> +
```
SimpleCov.start do
  minimum_coverage 90
  add_filter '/spec/'
end
```

2022-03-10 12:50 UTC, YaroslavZahoruiko requested changes

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on .bundler-audit.yml
> +  -
i think you can remove this file

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on .fasterer.yml
> +  - "config/**/*"
i think you don't need to exclude this folder

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on .rubocop.yml
> +    -
remove '-' and add empty line in end file

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/admin/books.rb
> +    column(:author) { |book| book.author.name }
return back to first_name and last_name and define full_name method in decorator

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/admin/books.rb
> +      # end
why comment?

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/controllers/addresses_controller.rb
>    def update
what is "def check"?
you need follow REST

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/controllers/addresses_controller.rb
>        end
you need move business logic from controller to service object

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/controllers/books_controller.rb
> +    load_more if request.xhr?
move to service object
12 - magic number, need move to constant

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/controllers/books_controller.rb
> +    load_more if request.xhr?
in def show
@reviews = @book.reviews.approved

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/controllers/users/my_registrations_controller.rb
> +      UserMailer.welcome_send(current_user).deliver if current_user
for email need use sidekiq

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/mailers/user_mailer.rb
>    def welcome_send(user)
please add empty line before method

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/models/book.rb
> +  has_many_attached :covers
you need to create a new model Image and do has_many :images

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/_books.haml
> +    = link_to "View More", pagy_url_for(@pagy, @pagy.next), remote: true, class: "btn btn-primary mb-20 js_load_more_books"
please add empty line at end of file

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/javascript/controllers/books.js
> +});
what does it do?

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/_books.haml
> +                  -#%a.thumb-hover-link{href: carts_path(book_id: book.id, count: 1), "data-turbo-method": :post}
remove comment

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/_sort.haml
> +    %a{href: category_books_path(sort: sort)}= sort
please use link_to

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/_sort.haml
> +- SORT.each do |sort, _value|
each_key

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/index.haml
> +      %a.filter-link{href: category_books_path("all", sort: params[:sort])}
what is 'all' ?
take value from constant

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/show.haml
> +              = image_tag url_for(cover.variant(resize_to_fill: [297, 210]))
use derivatives

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/show.haml
> +              = image_tag url_for(cover.variant(resize_to_fill: [297, 210]))
read about gem 'shrine'

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on app/views/books/show.haml
>        %h3.mt-res-0 Category: #{@book.category.title}
all text should be in i18n

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on config/initializers/my_constants.rb
> +  "Newest first": "created_at",
move file to lib/constants.rb

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on config/initializers/my_constants.rb
> +  "Newest first": "created_at",
and use '' instead of ""
you need to change the rubocop config, you should get warnings about it

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on config/storage.yml
> +  bucket: <%= Rails.application.credentials.dig(:aws, :bucket) %>
when you add a shrine gem, you won't need it

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on db/migrate/20220221113130_create_active_storage_tables.active_storage.rb
> +      else
redo through shrine

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on db/migrate/20220221232310_update_authors_name.rb
> +end
return back

2022-03-10 12:50 UTC, YaroslavZahoruiko commented on spec/controllers/addresses_spec.rb
> +  # describe "PUT check" do
add empty line between describe, context, it,

2022-03-18 11:23 UTC, YaroslavZahoruiko requested changes

2022-03-18 11:23 UTC, YaroslavZahoruiko commented on config/initializers/shrine.rb
> +                    }
move to config/environments/test.rb

2022-03-18 11:23 UTC, YaroslavZahoruiko commented on config/initializers/shrine.rb
> +                  end
move to config/environments/development.rb / production.rb

2022-03-18 11:23 UTC, YaroslavZahoruiko commented on config/routes.rb
> +  root 'home#home'
i think home#index would be better

2022-03-18 11:23 UTC, YaroslavZahoruiko commented on config/storage.yml
> +#test:
i think you can remove this file

2022-03-25 12:29 UTC, YaroslavZahoruiko commented on app/controllers/addresses_controller.rb
> +  def updated?
current_user.adresses.find(:id).update(permitted_params)

2022-03-25 12:29 UTC, YaroslavZahoruiko commented on app/models/cover.rb
> +  include ImageUploader::Attachment(:image)
belongs_to :user

2022-03-25 12:29 UTC, YaroslavZahoruiko commented on app/models/cover.rb
> +  include ImageUploader::Attachment(:image)
belongs_to :user

2022-03-25 12:29 UTC, YaroslavZahoruiko commented on app/uploaders/image_uploader.rb
> +end
add validation for images

2022-04-04 08:13 UTC, merged