Checkout
krossovok83/bookstore_per_step pull request #16
Opened 2022-04-26 16:15 UTC by krossovok83

Step 10
Checkout

2022-04-27 12:45 UTC, YaroslavZahoruiko requested changes

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on .rubocop.yml
> +    - 'app/models/concerns/order_state.rb'
please turn off rubocop in file
don't do it in the global config

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/models/concerns/order_state.rb
> +      state :canceled
i think you need
cart, address, delivery, payment, confirmation, delivered, cancelled

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/models/concerns/order_state.rb
> +      event :come_back do
pass_cart_step

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/models/concerns/order_state.rb
> +      event :filling do
pass_ address_step

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/javascript/views/checkout_address.js
> +// });
remove

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/helpers/application_helper.rb
> +  end
please do not use helpers

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/controllers/checkouts_controller.rb
> +  end
please move all business logic to service object

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/controllers/checkouts_controller.rb
> +  end
do you need edit action?

2022-04-27 12:45 UTC, YaroslavZahoruiko commented on app/services/order_services/current_order.rb
> +  class CurrentOrder < ApplicationService
This class is called current_order but in this class you are initializing the addresses, it violates the Single Responsibility Principle

2022-04-28 05:11 UTC, krossovok83 commented on app/models/concerns/order_state.rb
> +      state :canceled
if the question is about naming, then corrected
if to quantity:
created - cart - very convenient to validate the presence of orders in the cart
in_delivery - according to the task, it must be present

2022-04-28 11:11 UTC, YaroslavZahoruiko requested changes

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/checkout_services/check_state.rb
> +      end
perhaps we need to check for other parameters such as the presence of an address or order_items

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/checkout_services/order_confirm.rb
> +      "R#{8.times.map { rand(10) }.join}"
often use the creation date of the order for its number, and the code looks nice
"R#{Time.zone.now.to_s(:number)}"

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/checkout_services/update_addresses.rb
> +      @params[:use_billing] == '1' ? :billing_address_attributes : :shipping_address_attributes
what is '1' ?

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/checkout_services/update_step.rb
> +        (@session = 'delete')
remove session you can stay in controller
session[:order_id] = nil if order.confirmed?

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/order_services/current_order.rb
> +      OrderServices::BuildAddresses.call(@order, @user) if @user
this is not necessary, put one line of code into a separate method

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/order_services/current_order.rb
> +      @order = Order.find_by(token: @token)
the same

2022-04-28 11:11 UTC, YaroslavZahoruiko commented on app/services/order_services/current_order.rb
> +      @order = Order.find_by(token: @token)
you can do that in TODO list in the trailblazer

2022-04-29 14:37 UTC, krossovok83 commented on app/models/concerns/order_state.rb
> +      state :created, initial: true
for validation on a non-empty cart

2022-05-02 09:29 UTC, YaroslavZahoruiko requested changes

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/controllers/checkouts_controller.rb
> +      redirect_to_next step
why, when your services fail, are you going to take the next step?

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/models/order.rb
> +  validates :delivery_id, presence: true, if: proc { delivery? }
i18n

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/services/checkout_services/check_state.rb
> +      when :delivery then @order.state == 'address'
constant

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/controllers/checkouts_controller.rb
> +  steps :addresses, :delivery, :payment, :confirm, :complete
STEPS = { addresses: 'addresses' }
steps STEPS[:addresses]

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/services/checkout_services/check_state.rb
> +      when :delivery then @order.state == 'address'
STEPS[:addresses]

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/services/checkout_services/check_state.rb
> +    def payment
your step is payment, why check that the order is in the delivery status?

2022-05-02 09:29 UTC, YaroslavZahoruiko commented on app/services/checkout_services/card_define.rb
> +      @order.build_card unless @order.card
i think you do not need service object for initialize card without any conditions

2022-05-04 19:43 UTC, YaroslavZahoruiko requested changes

2022-05-04 19:43 UTC, YaroslavZahoruiko commented on app/controllers/checkouts_controller.rb
> +    end
move to service object

2022-05-04 19:43 UTC, YaroslavZahoruiko commented on app/controllers/orders_controller.rb
> +  before_action :to_cart_state
move to service object

2022-05-04 19:43 UTC, YaroslavZahoruiko commented on app/controllers/orders_controller.rb
> +    result = OrderServices::ToCheckout.new(current_order)
what do you mean by ToCheckout? it's a bad name for a service

2022-05-12 08:32 UTC, YaroslavZahoruiko approved these changes

2022-05-12 09:09 UTC, merged